In [1]:
import xgboost as xgb 
from xgboost import XGBClassifier, plot_importance
from sklearn.model_selection import train_test_split
import warnings
import pandas as pd
warnings.filterwarnings('ignore')

df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

disease_list = df.SUBCLASS.unique()
df_target = df['SUBCLASS']

data = df.drop(columns=['ID', 'SUBCLASS'])
df_test.drop(columns=['ID'], inplace=True)
data

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2,R895R,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6197,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6198,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,T181S,WT
6199,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6200,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [ ]:
df_ = data.copy()
df_['SUBCLASS'] = df.loc[:, df.columns[1:2]]
for d in disease_list:
    count_df = df_[df_.SUBCLASS==d].apply(lambda x : x!='WT').agg(sum)
    count_df = count_df[2:].reset_index(name='count').sort_values(by='count',ascending=False)
    gl = count_df[count_df['count']>0][1:]['index']
    print(d , len(list(gl))) #, gl)

In [11]:
cdf = get_count_df(df, 'OV')
cdf

3469      RYR2
881     COL6A3
3468      RYR1
2994     PKHD1
1243      EGFR
         ...
34       ABHD2
38      ABI3BP
39        ABL1
54       ACKR1
55       ACKR3
Name: index, Length: 1957, dtype: object

In [15]:
'ID' in list(cdf)

False

In [26]:
def get_count_df(df, d, th):
    count_df = df[df.SUBCLASS==d].apply(lambda x : x!='WT').agg(sum)
    count_df = count_df[2:].reset_index(name='count').sort_values(by='count',ascending=False)
    gl = count_df[count_df['count']>th][1:]['index']
    return gl
from collections import defaultdict
expert_dict = defaultdict()

df_ = data.copy()

df_['SUBCLASS'] = df.loc[:, df.columns[1:2]]
for d in disease_list:
    all_g = set(df[df.SUBCLASS==d].columns)
    gl = get_count_df(df_, d, 1)
    try:
        g_expert = pd.read_csv('./reference_data/'+d+'.csv')
        aa = set(g_expert['g.name'])        
        
    except FileNotFoundError:
        aa = set(get_count_df(df_, d, 5))
        
    expdict = all_g.intersection(aa)
    expert_dict[d] = expdict
    print(d,  len(list(gl)), len(aa), len(expdict))

KIPAN 1873 699 307
SARC 513 69 38
SKCM 3533 69 31
KIRC 1050 132 69
GBMLGG 1131 181 117
STES 3650 69 38
BRCA 2625 1004 497
THCA 197 58 34
LIHC 1161 179 104
HNSC 1948 55 37
PAAD 983 628 287
OV 818 317 133
PRAD 370 611 311
UCEC 3641 89 54
LAML 49 1007 493
COAD 2950 557 278
ACC 555 38 23
LGG 288 111 53
LUSC 2399 629 246
LUAD 2116 467 467
CESC 1652 42 22
PCPG 72 3 3
THYM 30 19 10
BLCA 1774 121 70
TGCT 430 23 9
DLBC 553 9 4

In [36]:
#preprocessing for total
#for model csv
total = pd.concat([data,df_test])
f = lambda x : '' if x == 'WT' else str(x)
total = total.map(f)

In [7]:
total

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,R89,,,,,,,,,,...,,,,,,,,,,
3,,,,,,,,,,,...,,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,,,,,,,,,,,...,,,,,,,,,,
2542,,,,,,,,,,,...,,,,,,,,,,
2543,,,,,,L21,P22,R5M,G60,I24,...,S20,L23,,,L30,,N25,G67,,
2544,,,,,,,,,R15,,...,,,,,,,,,,
2545,,,,,,,,,,,...,,,,,,,,,,

In [7]:
### ###
nCols = len(data.columns)
from collections import defaultdict
cDic = defaultdict()
for i, c in enumerate(data.columns):
    cDic[i] = c

In [8]:
def make_ndf (data, df_test):
    #data.drop('SUBCLASS', axis=1,inplace=True)
    #target = pd.concat([data,df_test])
    
    #2칸=>1칸
    ndf = pd.DataFrame()
    
    for i in range(nCols//2):
        ndf[cDic[i*2]] = total[total.columns[i*2]] +' '+ total[total.columns[(i*2+1)]]
    return ndf

In [ ]:
#preprocessing
#for writing csv
def preprocessing_for_writing():
    f = lambda x : '' if x == 'WT' else x
    tdf = data.map(f)
    tdf['SUBCLASS'] = df.loc[:, df.columns[1:2]]
    tdf

In [9]:
df.loc[:, df.columns[:2]]

              ID SUBCLASS
0     TRAIN_0000    KIPAN
1     TRAIN_0001     SARC
2     TRAIN_0002     SKCM
3     TRAIN_0003     KIRC
4     TRAIN_0004   GBMLGG
...          ...      ...
6196  TRAIN_6196     LUAD
6197  TRAIN_6197      LGG
6198  TRAIN_6198     COAD
6199  TRAIN_6199     TGCT
6200  TRAIN_6200     SKCM

[6201 rows x 2 columns]

In [459]:
def getnDF(d):
    #2칸=>1칸
    ndf = pd.DataFrame()
    target = tdf[tdf['SUBCLASS']==d]
    target.drop('SUBCLASS', axis=1,inplace=True)
    for i in range(nCols//2):
        ndf[cDic[i*2]] = target[target.columns[i*2]] +' '+ target[target.columns[(i*2+1)]]
    return ndf

In [467]:
#for writing
for d in tdf['SUBCLASS'].unique():
    ndf = getnDF(d)
    for c in ndf.columns:
        ndf[c] = ndf[c].apply(lambda x : '-' if (x =='' or x==' ') else 'X')
    ndf.to_csv('./data1/bstr-'+d+'-1.csv')

In [308]:
a = [1,2,3,4,5,6,7,8]
for i in range (0,len(a)//2):
    print(i*2, (i+1)*2)

0 2
2 4
4 6
6 8

In [398]:
#2칸=>1칸
ndf = pd.DataFrame()
for i in range(10): #range(nCols//2):
    print(i, i+1) 
    #ndf[cDic[i*2]] =  data[data.columns[ i*2] or data.columns[  (i+1) * 2]]

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10

In [403]:
#2칸=>1칸
ndf = pd.DataFrame()
for i in range(10): #range(nCols//2):
    print(i*2, i*2 +1) 
    #ndf[cDic[i*2]] =  data[data.columns[ i*2] or data.columns[  (i+1) * 2]]

0 1
2 3
4 5
6 7
8 9
10 11
12 13
14 15
16 17
18 19

In [404]:
#2칸=>1칸
ndf = pd.DataFrame()
for i in  range(nCols//2):
    ndf[cDic[i*2]] = data[data.columns[i*2]] +' '+ data[data.columns[(i*2+1)]]
    #print(i*2, (i+1) * 2) 
    #strr = data[data.columns[i*2]] data[data.columns[ (i+1) * 2]]
    #ndf[cDic[i*2]] =  data[data.columns[ i*2] or data.columns[  (i+1) * 2]]  
ndf

,A2M,AADAT,ABAT,ABCA2,ABCA4,ABCA6,ABCA9,ABCB11,ABCB6,ABCB8,...,ZC3H14,ZFP36,ZFPM2,ZMIZ1,ZNF185,ZNF292,ZNF639,ZNFX1,ZPBP,ZWINT
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,R895R,,,,,,,T426T,,,...,,,,,,,,,,
3,,,,,,,,,,,...,Y904H,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,,,,,,,,,,L101M,...,,,,,,,,,,
6197,,,,,,,,,,,...,,,,,,,,,,
6198,,,,,,,,,,,...,,,,,,,,,,T181S
6199,,,,,,,,,,,...,,,,,,,,,,
6200,,,,,,,L31*,,,,...,,,,,,,,,,

In [405]:
ndf

,A2M,AADAT,ABAT,ABCA2,ABCA4,ABCA6,ABCA9,ABCB11,ABCB6,ABCB8,...,ZC3H14,ZFP36,ZFPM2,ZMIZ1,ZNF185,ZNF292,ZNF639,ZNFX1,ZPBP,ZWINT
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,R895R,,,,,,,T426T,,,...,,,,,,,,,,
3,,,,,,,,,,,...,Y904H,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,,,,,,,,,,L101M,...,,,,,,,,,,
6197,,,,,,,,,,,...,,,,,,,,,,
6198,,,,,,,,,,,...,,,,,,,,,,T181S
6199,,,,,,,,,,,...,,,,,,,,,,
6200,,,,,,,L31*,,,,...,,,,,,,,,,

In [424]:
cDic

defaultdict(None,
            {0: 'A2M',
             1: 'AAAS',
             2: 'AADAT',
             3: 'AARS1',
             4: 'ABAT',
             5: 'ABCA1',
             6: 'ABCA2',
             7: 'ABCA3',
             8: 'ABCA4',
             9: 'ABCA5',
             10: 'ABCA6',
             11: 'ABCA8',
             12: 'ABCA9',
             13: 'ABCB1',
             14: 'ABCB11',
             15: 'ABCB4',
             16: 'ABCB6',
             17: 'ABCB7',
             18: 'ABCB8',
             19: 'ABCB9',
             20: 'ABCC1',
             21: 'ABCC2',
             22: 'ABCC3',
             23: 'ABCC4',
             24: 'ABCC5',
             25: 'ABCC8',
             26: 'ABCD1',
             27: 'ABCD2',
             28: 'ABCD3',
             29: 'ABCE1',
             30: 'ABCF2',
             31: 'ABCG2',
             32: 'ABCG4',
             33: 'ABCG8',
             34: 'ABHD2',
             35: 'ABHD4',
             36: 'ABHD6',
             37: 'ABI1',
             38: 'ABI3BP',
             39: 'ABL1',
             40: 'ABLIM1',
             41: 'ABR',
             42: 'ACAA1',
             43: 'ACAA2',
             44: 'ACACA',
             45: 'ACADL',
             46: 'ACADM',
             47: 'ACADS',
             48: 'ACADSB',
             49: 'ACADVL',
             50: 'ACAT1',
             51: 'ACAT2',
             52: 'ACE',
             53: 'ACHE',
             54: 'ACKR1',
             55: 'ACKR3',
             56: 'ACLY',
             57: 'ACO2',
             58: 'ACOT2',
             59: 'ACOT8',
             60: 'ACOX1',
             61: 'ACOX2',
             62: 'ACOX3',
             63: 'ACP1',
             64: 'ACP2',
             65: 'ACP5',
             66: 'ACRBP',
             67: 'ACRV1',
             68: 'ACSL1',
             69: 'ACSL3',
             70: 'ACSL4',
             71: 'ACSL5',
             72: 'ACSL6',
             73: 'ACSM1',
             74: 'ACSM3',
             75: 'ACSS1',
             76: 'ACSS2',
             77: 'ACTA1',
             78: 'ACTA2',
             79: 'ACTB',
             80: 'ACTC1',
             81: 'ACTG1',
             82: 'ACTG2',
             83: 'ACTL7B',
             84: 'ACTN1',
             85: 'ACTN2',
             86: 'ACTN3',
             87: 'ACTN4',
             88: 'ACTR2',
             89: 'ACTR3',
             90: 'ACVR1',
             91: 'ACVR1B',
             92: 'ACVR2A',
             93: 'ACVRL1',
             94: 'ADA',
             95: 'ADAD1',
             96: 'ADAM10',
             97: 'ADAM12',
             98: 'ADAM15',
             99: 'ADAM17',
             100: 'ADAM19',
             101: 'ADAM2',
             102: 'ADAM23',
             103: 'ADAM8',
             104: 'ADAM9',
             105: 'ADAMDEC1',
             106: 'ADAMTS1',
             107: 'ADAMTS5',
             108: 'ADAR',
             109: 'ADCY1',
             110: 'ADCY2',
             111: 'ADCY6',
             112: 'ADCY9',
             113: 'ADCYAP1',
             114: 'ADD1',
             115: 'ADD2',
             116: 'ADD3',
             117: 'ADGRA2',
             118: 'ADGRE1',
             119: 'ADGRG1',
             120: 'ADGRL2',
             121: 'ADGRL4',
             122: 'ADH1C',
             123: 'ADH4',
             124: 'ADH5',
             125: 'ADH7',
             126: 'ADIG',
             127: 'ADIPOQ',
             128: 'ADIPOR1',
             129: 'ADIPOR2',
             130: 'ADM',
             131: 'ADORA2B',
             132: 'ADRA1B',
             133: 'ADRA2B',
             134: 'ADRA2C',
             135: 'ADRM1',
             136: 'ADSL',
             137: 'AEBP1',
             138: 'AEN',
             139: 'AFAP1L2',
             140: 'AFF1',
             141: 'AFG3L2',
             142: 'AGER',
             143: 'AGFG1',
             144: 'AGGF1',
             145: 'AGL',
             146: 'AGO2',
             147: 'AGO4',
             148: 'AGPAT3',
             149: 'AGPAT4',
             150: 'AGR2',
             151: 'AGRN',
             152: 'AGXT',
             153: 'AHCY',
             154: 'AHNAK',
             155: 'AHR',
             156: 'AHSP',
             157: 'AIFM1',
             158: 'AIFM3',
             159: 'AIMP2',
             160: 'AK1',
             161: 'AK2',
             162: 'AK3',
             163: 'AK4',
             164: 'AKAP1',
             165: 'AKAP10',
             166: 'AKAP12',
             167: 'AKAP13',
             168: 'AKAP4',
             169: 'AKAP7',
             170: 'AKR1A1',
             171: 'AKR1B10',
             172: 'AKR1C2',
             173: 'AKR1C3',
             174: 'AKR1D1',
             175: 'AKT1',
             176: 'AKT1S1',
             177: 'AKT2',
             178: 'AKT3',
             179: 'ALAD',
             180: 'ALAS1',
             181: 'ALAS2',
             182: 'ALB',
             183: 'ALCAM',
             184: 'ALDH18A1',
             185: 'ALDH1A1',
             186: 'ALDH1A2',
             187: 'ALDH1A3',
             188: 'ALDH1L1',
             189: 'ALDH2',
             190: 'ALDH3A1',
             191: 'ALDH3A2',
             192: 'ALDH3B1',
             193: 'ALDH6A1',
             194: 'ALDH7A1',
             195: 'ALDH8A1',
             196: 'ALDH9A1',
             197: 'ALDOA',
             198: 'ALDOB',
             199: 'ALDOC',
             200: 'ALG1',
             201: 'ALMS1',
             202: 'ALOX12B',
             203: 'ALOX15',
             204: 'ALOX15B',
             205: 'ALS2',
             206: 'ALYREF',
             207: 'AMACR',
             208: 'AMBN',
             209: 'AMD1',
             210: 'AMFR',
             211: 'AMH',
             212: 'AMIGO1',
             213: 'AMIGO2',
             214: 'AMMECR1',
             215: 'AMOT',
             216: 'AMPD3',
             217: 'AMPH',
             218: 'ANG',
             219: 'ANGPT1',
             220: 'ANGPTL3',
             221: 'ANGPTL4',
             222: 'ANK1',
             223: 'ANKH',
             224: 'ANKRA2',
             225: 'ANKRD2',
             226: 'ANKZF1',
             227: 'ANLN',
             228: 'ANO1',
             229: 'ANP32E',
             230: 'ANPEP',
             231: 'ANTXR2',
             232: 'ANXA1',
             233: 'ANXA10',
             234: 'ANXA13',
             235: 'ANXA2',
             236: 'ANXA4',
             237: 'ANXA5',
             238: 'ANXA9',
             239: 'AOC3',
             240: 'AOX1',
             241: 'AP1G1',
             242: 'AP2B1',
             243: 'AP2M1',
             244: 'AP2S1',
             245: 'AP3B1',
             246: 'AP3S1',
             247: 'AP4B1',
             248: 'APAF1',
             249: 'APBB1',
             250: 'APBB2',
             251: 'APC',
             252: 'APEX1',
             253: 'APH1A',
             254: 'APLNR',
             255: 'APLP1',
             256: 'APLP2',
             257: 'APOA1',
             258: 'APOA4',
             259: 'APOBEC3F',
             260: 'APOBEC3G',
             261: 'APOC1',
             262: 'APOC2',
             263: 'APOC3',
             264: 'APOD',
             265: 'APOE',
             266: 'APOH',
             267: 'APOL6',
             268: 'APOM',
             269: 'APP',
             270: 'APPBP2',
             271: 'APRT',
             272: 'AQP3',
             273: 'AQP7',
             274: 'AQP9',
             275: 'AR',
             276: 'ARAF',
             277: 'ARAP3',
             278: 'ARCN1',
             279: 'AREG',
             280: 'ARF1',
             281: 'ARF4',
             282: 'ARF6',
             283: 'ARFGAP1',
             284: 'ARFGAP3',
             285: 'ARFGEF1',
             286: 'ARFGEF2',
             287: 'ARFIP1',
             288: 'ARFIP2',
             289: 'ARG1',
             290: 'ARG2',
             291: 'ARHGAP10',
             292: 'ARHGAP27',
             293: 'ARHGAP29',
             294: 'ARHGAP4',
             295: 'ARHGAP5',
             296: 'ARHGDIA',
             297: 'ARHGDIG',
             298: 'ARHGEF11',
             299: 'ARHGEF12',
             300: 'ARHGEF2',
             301: 'ARHGEF3',
             302: 'ARHGEF6',
             303: 'ARHGEF7',
             304: 'ARHGEF9',
             305: 'ARID4A',
             306: 'ARID4B',
             307: 'ARID5B',
             308: 'ARL2BP',
             309: 'ARL3',
             310: 'ARL4A',
             311: 'ARL6IP1',
             312: 'ARL8A',
             313: 'ARPC2',
             314: 'ARPC3',
             315: 'ARPC5L',
             316: 'ARPP19',
             317: 'ARPP21',
             318: 'ARRB1',
             319: 'ARRB2',
             320: 'ART3',
             321: 'ARTN',
             322: 'ASB13',
             323: 'ASB7',
             324: 'ASCL1',
             325: 'ASF1A',
             326: 'ASF1B',
             327: 'ASL',
             328: 'ASNS',
             329: 'ASS1',
             330: 'ATAD2',
             331: 'ATF1',
             332: 'ATF3',
             333: 'ATF4',
             334: 'ATF5',
             335: 'ATF6',
             336: 'ATG10',
             337: 'ATG4A',
             338: 'ATG4B',
             339: 'ATL2',
             340: 'ATOH8',
             341: 'ATOX1',
             342: 'ATP1A1',
             343: 'ATP1A3',
             344: 'ATP1B1',
             345: 'ATP1B3',
             346: 'ATP2A1',
             347: 'ATP2A2',
             348: 'ATP2B1',
             349: 'ATP2B4',
             350: 'ATP2C1',
             351: 'ATP4A',
             352: 'ATP5F1A',
             353: 'ATP5F1B',
             354: 'ATP5F1C',
             355: 'ATP5F1D',
             356: 'ATP5F1E',
             357: 'ATP5MC1',
             358: 'ATP5MC2',
             359: 'ATP5MC3',
             360: 'ATP5ME',
             361: 'ATP5MF',
             362: 'ATP5MG',
             363: 'ATP5PB',
             364: 'ATP5PD',
             365: 'ATP5PF',
             366: 'ATP5PO',
             367: 'ATP6AP1',
             368: 'ATP6V0A1',
             369: 'ATP6V0A4',
             370: 'ATP6V0B',
             371: 'ATP6V0C',
             372: 'ATP6V0D1',
             373: 'ATP6V0E1',
             374: 'ATP6V1B1',
             375: 'ATP6V1C1',
             376: 'ATP6V1D',
             377: 'ATP6V1E1',
             378: 'ATP6V1F',
             379: 'ATP6V1G1',
             380: 'ATP6V1H',
             381: 'ATP7A',
             382: 'ATP8B1',
             383: 'ATRN',
             384: 'ATRX',
             385: 'ATXN1',
             386: 'ATXN2',
             387: 'AUH',
             388: 'AURKA',
             389: 'AURKB',
             390: 'AUTS2',
             391: 'AVL9',
             392: 'AVPR1A',
             393: 'AXIN1',
             394: 'AXIN2',
             395: 'AXL',
             396: 'AZGP1',
             397: 'B2M',
             398: 'B3GALT6',
             399: 'B3GAT1',
             400: 'B3GAT3',
             401: 'B3GNT3',
             402: 'B4GALNT2',
             403: 'B4GALT1',
             404: 'B4GALT2',
             405: 'B4GALT4',
             406: 'B4GALT5',
             407: 'B4GALT7',
             408: 'BACH1',
             409: 'BAG1',
             410: 'BAG3',
             411: 'BAIAP2',
             412: 'BAK1',
             413: 'BANF1',
             414: 'BANK1',
             415: 'BARD1',
             416: 'BASP1',
             417: 'BATF',
             418: 'BATF2',
             419: 'BATF3',
             420: 'BAX',
             421: 'BAZ2A',
             422: 'BBOX1',
             423: 'BCAM',
             424: 'BCAN',
             425: 'BCAP31',
             426: 'BCAR1',
             427: 'BCAR3',
             428: 'BCAT1',
             429: 'BCKDHA',
             430: 'BCKDHB',
             431: 'BCL10',
             432: 'BCL11B',
             433: 'BCL2',
             434: 'BCL2A1',
             435: 'BCL2L1',
             436: 'BCL2L10',
             437: 'BCL2L11',
             438: 'BCL2L13',
             439: 'BCL2L2',
             440: 'BCL3',
             441: 'BCL6',
             442: 'BCR',
             443: 'BDH2',
             444: 'BDKRB1',
             445: 'BDKRB2',
             446: 'BDNF',
             447: 'BEST1',
             448: 'BET1',
             449: 'BGN',
             450: 'BHLHE40',
             451: 'BID',
             452: 'BIK',
             453: 'BIN1',
             454: 'BIRC2',
             455: 'BIRC3',
             456: 'BIRC5',
             457: 'BLCAP',
             458: 'BLVRA',
             459: 'BLVRB',
             460: 'BMF',
             461: 'BMP1',
             462: 'BMP2',
             463: 'BMP2K',
             464: 'BMP6',
             465: 'BMPR1A',
             466: 'BMPR1B',
             467: 'BMPR2',
             468: 'BNIP3',
             469: 'BNIP3L',
             470: 'BOLA2',
             471: 'BPGM',
             472: 'BPHL',
             473: 'BPNT1',
             474: 'BRAF',
             475: 'BRCA1',
             476: 'BRCA2',
             477: 'BRDT',
             478: 'BRF2',
             479: 'BRMS1L',
             480: 'BRPF3',
             481: 'BRS3',
             482: 'BSG',
             483: 'BST2',
             484: 'BTBD3',
             485: 'BTC',
             486: 'BTG1',
             487: 'BTG2',
             488: 'BTG3',
             489: 'BTRC',
             490: 'BUB1',
             491: 'BUB1B',
             492: 'BUB3',
             493: 'BYSL',
             494: 'C1QA',
             495: 'C1QBP',
             496: 'C1QC',
             497: 'C1R',
             498: 'C1S',
             499: 'C2',
             500: 'C3',
             501: 'C3AR1',
             502: 'C4BPB',
             503: 'C5',
             504: 'C5AR1',
             505: 'C8A',
             506: 'C8B',
             507: 'C8G',
             508: 'C9',
             509: 'CA1',
             510: 'CA12',
             511: 'CA2',
             512: 'CA4',
             513: 'CA6',
             514: 'CAB39',
             515: 'CAB39L',
             516: 'CACNA1A',
             517: 'CACNA1B',
             518: 'CACNA1F',
             519: 'CACNA1H',
             520: 'CACNA2D2',
             521: 'CACNG1',
             522: 'CACYBP',
             523: 'CAD',
             524: 'CADM1',
             525: 'CADM2',
             526: 'CADM3',
             527: 'CALB2',
             528: 'CALCB',
             529: 'CALCR',
             530: 'CALCRL',
             531: 'CALD1',
             532: 'CALM1',
             533: 'CALM3',
             534: 'CALML5',
             535: 'CALR',
             536: 'CALU',
             537: 'CAMK1D',
             538: 'CAMK2B',
             539: 'CAMK4',
             540: 'CAMKK2',
             541: 'CANT1',
             542: 'CANX',
             543: 'CAP1',
             544: 'CAP2',
             545: 'CAPG',
             546: 'CAPN2',
             547: 'CAPN3',
             548: 'CAPN5',
             549: 'CAPN9',
             550: 'CAPZB',
             551: 'CARTPT',
             552: 'CASP1',
             553: 'CASP10',
             554: 'CASP2',
             555: 'CASP3',
             556: 'CASP4',
             557: 'CASP5',
             558: 'CASP6',
             559: 'CASP7',
             560: 'CASP8',
             561: 'CASP8AP2',
             562: 'CASP9',
             563: 'CASQ1',
             564: 'CASQ2',
             565: 'CAST',
             566: 'CAT',
             567: 'CAV1',
             568: 'CAV2',
             569: 'CAV3',
             570: 'CAVIN1',
             571: 'CAVIN2',
             572: 'CAVIN3',
             573: 'CBFA2T3',
             574: 'CBL',
             575: 'CBLB',
             576: 'CBR1',
             577: 'CBR3',
             578: 'CBR4',
             579: 'CBS',
             580: 'CBX1',
             581: 'CBX3',
             582: 'CBX5',
             583: 'CBX8',
             584: 'CCDC106',
             585: 'CCDC28A',
             586: 'CCDC88A',
             587: 'CCK',
             588: 'CCL11',
             589: 'CCL13',
             590: 'CCL17',
             591: 'CCL19',
             592: 'CCL2',
             593: 'CCL20',
             594: 'CCL22',
             595: 'CCL24',
             596: 'CCL25',
             597: 'CCL4',
             598: 'CCL5',
             599: 'CCL7',
             600: 'CCN1',
             601: 'CCN2',
             602: 'CCN5',
             603: 'CCNA1',
             604: 'CCNA2',
             605: 'CCNB2',
             606: 'CCND1',
             607: 'CCND2',
             608: 'CCND3',
             609: 'CCNE1',
             610: 'CCNF',
             611: 'CCNG1',
             612: 'CCNG2',
             613: 'CCNK',
             614: 'CCNL1',
             615: 'CCNO',
             616: 'CCNT1',
             617: 'CCP110',
             618: 'CCR1',
             619: 'CCR2',
             620: 'CCR4',
             621: 'CCR5',
             622: 'CCR7',
             623: 'CCR8',
             624: 'CCRL2',
             625: 'CCSER2',
             626: 'CCT2',
             627: 'CCT3',
             628: 'CCT4',
             629: 'CCT5',
             630: 'CCT6A',
             631: 'CCT6B',
             632: 'CCT7',
             633: 'CD14',
             634: 'CD151',
             635: 'CD160',
             636: 'CD1D',
             637: 'CD2',
             638: 'CD207',
             639: 'CD209',
             640: 'CD247',
             641: 'CD274',
             642: 'CD276',
             643: 'CD28',
             644: 'CD2AP',
             645: 'CD302',
             646: 'CD34',
             647: 'CD36',
             648: 'CD37',
             649: 'CD38',
             650: 'CD3D',
             651: 'CD3E',
             652: 'CD3G',
             653: 'CD4',
             654: 'CD40',
             655: 'CD40LG',
             656: 'CD44',
             657: 'CD46',
             658: 'CD47',
             659: 'CD48',
             660: 'CD55',
             661: 'CD59',
             662: 'CD63',
             663: 'CD69',
             664: 'CD7',
             665: 'CD70',
             666: 'CD74',
             667: 'CD79A',
             668: 'CD79B',
             669: 'CD80',
             670: 'CD81',
             671: 'CD82',
             672: 'CD83',
             673: 'CD86',
             674: 'CD8A',
             675: 'CD8B',
             676: 'CD9',
             677: 'CD96',
             678: 'CD99',
             679: 'CDA',
             680: 'CDADC1',
             681: 'CDC14B',
             682: 'CDC20',
             683: 'CDC25A',
             684: 'CDC25B',
             685: 'CDC27',
             686: 'CDC34',
             687: 'CDC42',
             688: 'CDC42BPA',
             689: 'CDC42EP1',
             690: 'CDC42EP2',
             691: 'CDC42EP4',
             692: 'CDC42SE2',
             693: 'CDC45',
             694: 'CDC5L',
             695: 'CDC6',
             696: 'CDC7',
             697: 'CDCA3',
             698: 'CDCA8',
             699: 'CDCP1',
             700: 'CDH1',
             701: 'CDH11',
             702: 'CDH13',
             703: 'CDH15',
             704: 'CDH16',
             705: 'CDH2',
             706: 'CDH3',
             707: 'CDH4',
             708: 'CDH6',
             709: 'CDH8',
             710: 'CDK1',
             711: 'CDK13',
             712: 'CDK2',
             713: 'CDK4',
             714: 'CDK5R1',
             715: 'CDK5RAP2',
             716: 'CDK6',
             717: 'CDK7',
             718: 'CDK8',
             719: 'CDK9',
             720: 'CDKAL1',
             721: 'CDKN1A',
             722: 'CDKN1B',
             723: 'CDKN1C',
             724: 'CDKN2A',
             725: 'CDKN2AIP',
             726: 'CDKN2B',
             727: 'CDKN2C',
             728: 'CDKN2D',
             729: 'CDKN3',
             730: 'CDO1',
             731: 'CDON',
             732: 'CDR2',
             733: 'CDSN',
             734: 'CEBPA',
             735: 'CEBPB',
             736: 'CEBPD',
             737: 'CEBPG',
             738: 'CEL',
             739: 'CELF2',
             740: 'CELSR1',
             741: 'CELSR2',

In [426]:
ndf

,A2M,AADAT,ABAT,ABCA2,ABCA4,ABCA6,ABCA9,ABCB11,ABCB6,ABCB8,...,ZC3H14,ZFP36,ZFPM2,ZMIZ1,ZNF185,ZNF292,ZNF639,ZNFX1,ZPBP,ZWINT
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,R895R,,,,,,,T426T,,,...,,,,,,,,,,
3,,,,,,,,,,,...,Y904H,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,,,,,,,,,,L101M,...,,,,,,,,,,
6197,,,,,,,,,,,...,,,,,,,,,,
6198,,,,,,,,,,,...,,,,,,,,,,T181S
6199,,,,,,,,,,,...,,,,,,,,,,
6200,,,,,,,L31*,,,,...,,,,,,,,,,

In [411]:
#df[df.columns[1::2]]
#df[df.columns[0::2]]

In [351]:
df[df.ABCB8 !='WT']

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
14,TRAIN_0014,SKCM,WT,WT,WT,WT,WT,F157L S1042F,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
354,TRAIN_0354,DLBC,A615A,WT,WT,WT,WT,R1228R P2150P,WT,V150V,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
468,TRAIN_0468,OV,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
489,TRAIN_0489,CESC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
532,TRAIN_0532,LUSC,WT,WT,WT,WT,WT,WT,R2400W A903S,WT,...,E2679*,WT,WT,WT,WT,WT,WT,WT,WT,WT
562,TRAIN_0562,BLCA,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
717,TRAIN_0717,STES,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,Y46H,WT,WT
843,TRAIN_0843,SKCM,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,S1244N,WT,WT,WT,WT,WT
1138,TRAIN_1138,BRCA,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1369,TRAIN_1369,SKCM,E1311K E342K R147C E1311K E342K R147C,P307S T163T P307S T163T,P244L P244L,WT,P239S P239S,P91S P91S,S1492F A1262A F1948F S1237F L1683L S1492F A126...,G495G P72L L310L D1089D G495G P72L L310L D1089D,...,P873S L2423V R2173* S1473F P873S L2423V R2173*...,E54K E54K,WT,WT,F380F S197F F380F S197F,G378S L264L P349P G121I I207I G378S L264L P349...,E143K E143K,L489L L489L,WT,WT
1502,TRAIN_1502,COAD,R360R,WT,WT,WT,D314G,WT,WT,WT,...,K162T S664S A779V T1526M L1806V R2115*,WT,WT,WT,Q1572Q H730Q I688I,WT,R258I,WT,WT,WT
1620,TRAIN_1620,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,L477L,WT,WT,WT,WT,WT
1747,TRAIN_1747,STES,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1818,TRAIN_1818,COAD,R174H,WT,WT,WT,WT,WT,WT,WT,...,A1913D,WT,WT,WT,WT,WT,WT,WT,WT,WT
2055,TRAIN_2055,CESC,WT,S198F,WT,WT,WT,WT,WT,WT,...,V435I,WT,WT,WT,WT,WT,L142L,WT,WT,WT
2155,TRAIN_2155,OV,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2335,TRAIN_2335,GBMLGG,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2343,TRAIN_2343,BRCA,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2361,TRAIN_2361,COAD,WT,WT,WT,WT,WT,WT,WT,L617R R108C,...,WT,WT,WT,WT,A1742G,WT,WT,WT,WT,WT
2463,TRAIN_2463,BLCA,WT,WT,WT,WT,WT,T1401I,V1827V,WT,...,WT,WT,D67N,WT,WT,WT,WT,L166L,WT,WT
2477,TRAIN_2477,BRCA,G852R,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,R162C,WT,WT,WT,WT
2920,TRAIN_2920,ACC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2999,TRAIN_2999,STES,S1102S S150S,G299D,WT,WT,WT,A343T F797fs,WT,T25M,...,L2341L F2488F N2538fs,R270Q,WT,WT,T1904M,A20A A118V,WT,D442V,WT,WT
3063,TRAIN_3063,STES,H582H,WT,WT,WT,WT,WT,WT,WT,...,L2245L,WT,WT,WT,WT,WT,R154C,WT,WT,WT
3069,TRAIN_3069,BLCA,R1122H,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3090,TRAIN_3090,STES,WT,WT,WT,WT,WT,WT,WT,WT,...,E2536fs,WT,WT,WT,WT,WT,WT,WT,WT,WT
3096,TRAIN_3096,STES,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,R246C,WT,WT,WT,WT,WT,WT
3106,TRAIN_3106,UCEC,WT,WT,WT,WT,WT,WT,H917Y,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3129,TRAIN_3129,SKCM,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3163,TRAIN_3163,BRCA,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3353,TRAIN_3353,UCEC,WT,WT,WT,WT,WT,WT,A769T,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3602,TRAIN_3602,KIRC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3666,TRAIN_3666,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3772,TRAIN_3772,BRCA,WT,WT,WT,WT,WT,W1747L,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3842,TRAIN_3842,COAD,WT,WT,WT,WT,WT,WT,WT,WT,...,Q204*,WT,WT,WT,WT,WT,WT,WT,WT,WT
3844,TRAIN_3844,STES,WT,WT,A351P,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4081,TRAIN_4081,COAD,P969S E840*,R478Q,WT,WT,WT,C1941C V983M R909Q R19I,WT,V1074V A427V L256L,...,F186V K693T N1110S T2126T R2316W,D152Y E264E K378N E18K,WT,WT,F1801L R906C I688I D663G R192W,R101W,WT,S662A,R128Q,P271H
4188,TRAIN_4188,TGCT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4189,TRAIN_4189,CESC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4210,TRAIN_4210,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,P96T,WT,WT,WT,WT,WT,WT,WT,WT
4223,TRAIN_4223,SKCM,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4371,TRAIN_4371,STES,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,R331H,WT,WT,WT
4587,TRAIN_4587,STES,M1385T,WT,WT,WT,WT,WT,T2283M S761F,E558K,...,Y694C,WT,WT,WT,WT,WT,WT,WT,WT,WT
4643,TRAIN_4643,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4729,TRAIN_4729,SKCM,WT,P523Q,WT,WT,WT,WT,WT,T274I P73S,...,Q945H,WT,WT,WT,WT,S375S,WT,P694P,WT,WT
4757,TRAIN_4757,UCEC,G706G T548I R174H,R330H C80F,S248F,WT,WT,M1091T V916V R500C,F1288F Y792Y,R1655C A1316T,...,S1111F K1632N S1747F C2409C,E238*,WT,R30M,V1612V E1611* C1288C F439C,V350M,G107V R91Q,WT,WT,D145N
4939,TRAIN_4939,STES,WT,WT,WT,WT,WT,WT,Y1051Y,WT,...,WT,WT,WT,WT,WT,R75Q,WT,WT,WT,WT
4952,TRAIN_4952,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4953,TRAIN_4953,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4984,TRAIN_4984,UCEC,WT,R194Q,WT,WT,WT,WT,A903T,L310I,...,F551V E1507K V2150V K2280T,P96P,P117H L432L,WT,C1441C M1234I,WT,WT,WT,WT,A525T
5041,TRAIN_5041,DLBC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
5660,TRAIN_5660,SKCM,WT,WT,WT,WT,WT,WT,F801F F1983F,WT,...,P1419P,WT,WT,WT,WT,WT,WT,WT,WT,WT
5900,TRAIN_5900,PAAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
5942,TRAIN_5942,SARC,S525S,WT,WT,WT,WT,WT,WT,P111S,...,WT,WT,WT,WT,WT,E318K,WT,WT,WT,WT
6043,TRAIN_6043,TGCT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6196,TRAIN_6196,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [359]:
df[df.ABCB8 !='WT']['SUBCLASS'].value_counts()

SUBCLASS
STES      10
SKCM       7
LUAD       6
COAD       5
BRCA       5
UCEC       4
CESC       3
BLCA       3
DLBC       2
OV         2
TGCT       2
LUSC       1
ACC        1
GBMLGG     1
KIRC       1
KIPAN      1
PAAD       1
SARC       1
Name: count, dtype: int64

In [314]:
data[data.columns[0*2]]

0          WT
1          WT
2       R895R
3          WT
4          WT
        ...
6196       WT
6197       WT
6198       WT
6199       WT
6200       WT
Name: A2M, Length: 6201, dtype: object

In [315]:
data[data.columns[2]]

0       WT
1       WT
2       WT
3       WT
4       WT
        ..
6196    WT
6197    WT
6198    WT
6199    WT
6200    WT
Name: AADAT, Length: 6201, dtype: object

In [305]:
data.loc[:, data.columns[2:4]]

     AADAT AARS1
0       WT    WT
1       WT    WT
2       WT    WT
3       WT    WT
4       WT    WT
...    ...   ...
6196    WT    WT
6197    WT    WT
6198    WT    WT
6199    WT    WT
6200    WT    WT

[6201 rows x 2 columns]

In [276]:
df

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,TRAIN_0000,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,TRAIN_0001,SARC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2,TRAIN_0002,SKCM,R895R,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,TRAIN_0003,KIRC,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,TRAIN_0004,GBMLGG,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,TRAIN_6196,LUAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6197,TRAIN_6197,LGG,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6198,TRAIN_6198,COAD,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,T181S,WT
6199,TRAIN_6199,TGCT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6200,TRAIN_6200,SKCM,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,TRAIN_0000,KIPAN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,TRAIN_0001,SARC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,TRAIN_0002,SKCM,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,TRAIN_0003,KIRC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,TRAIN_0004,GBMLGG,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,TRAIN_6196,LUAD,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6197,TRAIN_6197,LGG,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6198,TRAIN_6198,COAD,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6199,TRAIN_6199,TGCT,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6200,TRAIN_6200,SKCM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [190]:
data.loc[:, 'A2M']

0       0
1       0
2       1
3       0
4       0
       ..
6196    0
6197    0
6198    0
6199    0
6200    0
Name: A2M, Length: 6201, dtype: int64

In [197]:
data.loc[:, data.columns[0:3]]

      A2M  AAAS  AADAT
0       0     0      0
1       0     0      0
2       1     0      0
3       0     0      0
4       0     0      0
...   ...   ...    ...
6196    0     0      0
6197    0     0      0
6198    0     0      0
6199    0     0      0
6200    0     0      0

[6201 rows x 3 columns]

In [280]:
df.loc[:, df.columns[2:5]].agg(sum)

A2M      148
AAAS      44
AADAT     25
dtype: object

In [201]:
data.loc[:, data.columns[0:4]].agg(sum)

A2M      148
AAAS      44
AADAT     25
AARS1      0
dtype: int64

In [207]:
data

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6198,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [216]:
df[df.SUBCLASS == 'KIPAN']

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,TRAIN_0000,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
16,TRAIN_0016,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
17,TRAIN_0017,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
59,TRAIN_0059,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
66,TRAIN_0066,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,TRAIN_6132,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,S196G,WT,WT,WT,WT,WT
6137,TRAIN_6137,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6163,TRAIN_6163,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6186,TRAIN_6186,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6194,TRAIN_6194,KIPAN,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [215]:
target.loc[:, data.columns[0:1]].agg(sum)

A2M    WTWTWTWTWTWTWTWTWTWTWTWTS660RWTWTWTWTWTWTWTWTW...
dtype: object

In [ ]:
ndf = pd.DataFrame()
for i in range(0, 1): #len(glist)):
    if i != 0 or i != len(glist)-1:
        ndf[]
        #ndf[glist[i]] =
        
        
        
    #print(i, glist[i])

array(['KIPAN', 'SARC', 'SKCM', 'KIRC', 'GBMLGG', 'STES', 'BRCA', 'THCA',
       'LIHC', 'HNSC', 'PAAD', 'OV', 'PRAD', 'UCEC', 'LAML', 'COAD',
       'ACC', 'LGG', 'LUSC', 'LUAD', 'CESC', 'PCPG', 'THYM', 'BLCA',
       'TGCT', 'DLBC'], dtype=object)

In [61]:
df[df.SUBCLASS=='ACC']

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
30,TRAIN_0030,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,TRAIN_0044,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,TRAIN_0050,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
183,TRAIN_0183,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
656,TRAIN_0656,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5901,TRAIN_5901,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5917,TRAIN_5917,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6035,TRAIN_6035,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6082,TRAIN_6082,ACC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6148,TRAIN_6148,ACC,0,0,0,0,0,P1428P,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df[df.SUBCLASS=='ACC']['PLEC']

30                    A2113A L1321L
44             A2113A A2106A K2047*
50                               WT
183            A2113A A2106A L1321L
656                              WT
                   ...
5901                             WT
5917    A2113A A2106A A1697A L1321L
6035                         A2507A
6082                         A2495A
6148                             WT
Name: PLEC, Length: 72, dtype: object

In [69]:
da = df[df.SUBCLASS=='LAML']
cnt = []
for c in da.columns[2:]:
        cnt.append(da[c].apply(lambda x : x!=0).agg(sum))
max(cnt)

41

In [62]:

count_df = df[df.SUBCLASS=='LAML'].apply(lambda x : x!=0).agg(sum).sort_values(ascending=False).reset_index(name='count')
print(count_df)
total_rows = count_df[count_df['index']== 'ID']['count'].values[0]
print(count_df[count_df['count'] >= total_rows*0.75][2:])



#print(count_df[count_df['count']]>count_df['ID'])
#gene_list = count_df[count_df['count']>0]['index'].values
#print(len(gene_list))
#gene_list

         index  count
0           ID    158
1     SUBCLASS    158
2         NPM1     41
3         IDH1     18
4         IDH2     17
...        ...    ...
4381     ZNRF4      0
4382       A2M      0
4383      ZW10      0
4384     ZWINT      0
4385       ZYX      0

[4386 rows x 2 columns]
Empty DataFrame
Columns: [index, count]
Index: []

In [50]:
df[df.SUBCLASS=='SKCM'].apply(lambda x : x!='WT').columns

Index(['ID', 'SUBCLASS', 'A2M', 'AAAS', 'AADAT', 'AARS1', 'ABAT', 'ABCA1',
       'ABCA2', 'ABCA3',
       ...
       'ZNF292', 'ZNF365', 'ZNF639', 'ZNF707', 'ZNFX1', 'ZNRF4', 'ZPBP',
       'ZW10', 'ZWINT', 'ZYX'],
      dtype='object', length=4386)

In [74]:
def get_gene_list2():
    genes = []
    gene_set = set()
    for disease in df["SUBCLASS"].unique():
        disease_df = df[df["SUBCLASS"] == disease]

        non_wt_counts = (disease_df != 'WT').sum()  # "WT"가 아닌 행 개수
        non_wt_counts_sorted = non_wt_counts.sort_values(ascending=False) #빈도 수가 높은 순서대로 정렬

        n = 20 # 추출한 상위 유전자 개수
        genes.extend(list(non_wt_counts_sorted[2:2+n].index))

        #print(f'{disease} - 전체 행의 개수 : {len(disease_df)}')
        dd = non_wt_counts_sorted[2:n].reset_index()
        gene_list1 = dd['index'].values
        gene_set.update(gene_list1)
        #print(gene_list1)
    return gene_set

In [8]:
data

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2,R895R,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6197,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6198,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,T181S,WT
6199,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6200,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [10]:
df.loc[:, df.columns[1:2]]

     SUBCLASS
0       KIPAN
1        SARC
2        SKCM
3        KIRC
4      GBMLGG
...       ...
6196     LUAD
6197      LGG
6198     COAD
6199     TGCT
6200     SKCM

[6201 rows x 1 columns]

In [14]:
df_ = data.copy()
df_['SUBCLASS']= df.loc[:, df.columns[1:2]]
df_

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX,SUBCLASS
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,KIPAN
1,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,SARC
2,R895R,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,SKCM
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,KIRC
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,GBMLGG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,LUAD
6197,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,LGG
6198,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,T181S,WT,COAD
6199,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,TGCT
6200,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,SKCM

In [6]:
#### ####

In [22]:
diseaseList = df.SUBCLASS.value_counts().rename_axis('disease').reset_index(name='counts')
diseaseList

   disease  counts
0     BRCA     786
1    KIPAN     515
2   GBMLGG     461
3     STES     379
4     KIRC     334
5     THCA     324
6     SKCM     276
7     PRAD     266
8       OV     253
9      LGG     229
10    HNSC     223
11    COAD     223
12    UCEC     198
13    SARC     198
14    LUAD     184
15    LUSC     178
16    LIHC     158
17    LAML     158
18    CESC     155
19    PCPG     147
20    TGCT     124
21    PAAD     120
22    BLCA     104
23    THYM      98
24     ACC      72
25    DLBC      38

In [23]:
df[df.SUBCLASS == 'KIPAN'].shape[0]

515

In [12]:
data

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2,R895R,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6197,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6198,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,T181S,WT
6199,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6200,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [11]:
selected_genes = set()
for d in disease_list:
    df_ = data.copy()
    df_['SUBCLASS'] = df.loc[:, df.columns[1:2]]
    count_df = df_[df_.SUBCLASS==d].apply(lambda x : x!='WT').agg(sum)
    count_df = count_df[2:].reset_index(name='count')        
    #num_transaction = diseaseList[diseaseList.disease == d]['counts'].values[0]
    th = 5 #if num_transaction > 250 else 5
    #th = num_transaction//divider
    #print( num_transaction, th)
    
    gene_list = count_df[count_df['count']>th]['index'].values
    print(d, len(gene_list))
    selected_genes.update(gene_list)
print(len(selected_genes))

KIPAN 287
SARC 32
SKCM 2112
KIRC 69
GBMLGG 148
STES 2033
BRCA 691
THCA 5
LIHC 107
HNSC 334
PAAD 23
OV 48
PRAD 17
UCEC 2006
LAML 10
COAD 936
ACC 52
LGG 17
LUSC 587
LUAD 468
CESC 176
PCPG 4
THYM 2
BLCA 209
TGCT 15
DLBC 18
2924

In [29]:
if 'SUBCLASS' in selected_genes:
    print('ry')

In [12]:
selected_genes.remove("SUBCLASS")

In [13]:
total

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,R89,,,,,,,,,,...,,,,,,,,,,
3,,,,,,,,,,,...,,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,,,,,,,,,,,...,,,,,,,,,,
2542,,,,,,,,,,,...,,,,,,,,,,
2543,,,,,,L21,P22,R5M,G60,I24,...,S20,L23,,,L30,,N25,G67,,
2544,,,,,,,,,R15,,...,,,,,,,,,,
2545,,,,,,,,,,,...,,,,,,,,,,

In [28]:
#total = pd.concat([data,df_test] ) #make_ndf(data, df_test)
data = total[:6201]
total

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2,R895R,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2542,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2543,WT,WT,WT,WT,WT,L217I,P221P P251P,R5M,G606D,I248Nfs,...,S2049Vfs S1909Vfs,L232R,WT,WT,L305L,WT,N252I N251I,G679V,WT,WT
2544,WT,WT,WT,WT,WT,WT,WT,WT,R1517H,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2545,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [14]:
total = total.loc[:, list(selected_genes)]
total

,TRIB2,FOXC2,SLC25A23,CCNA1,EPHB3,CSF3,MEST,NEGR1,LAMB3,ABCB8,...,TLE4,MPP1,CALCR,AIFM1,MFSD6,TLE1,FOSL2,NOTCH4,JAG1,FKBP5
0,,N23,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,,,,,,,,,,
2,,,,,,,,,S62,,...,,,,,,,,,,
3,,,,,,,,,P12,,...,,,,,,,,,,
4,,,,,,,,,,,...,,,R42,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,,,,,P8P,,,,,,...,,,,,,,,,,
2542,,,,,,,,,,,...,,,,,,,,,,
2543,,,,,A44,L15,,,,R53,...,W58,,,,,P16,,D59,P73,
2544,,,,,,,,,,,...,,,,,,,,,,
2545,,,,,,,,,,,...,,,,,,,,,,

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for c in total.columns:
    total[c] = encoder.fit_transform(total[c])
#total[total.select_dtypes(include=['object']).columns] = df.select_dtypes(include=['object']).apply(lambda col: encoder.fit_transform(col))

In [17]:
df = total[:6201]
df_test = total[6201:]

In [18]:
df

,TRIB2,FOXC2,SLC25A23,CCNA1,EPHB3,CSF3,MEST,NEGR1,LAMB3,ABCB8,...,TLE4,MPP1,CALCR,AIFM1,MFSD6,TLE1,FOSL2,NOTCH4,JAG1,FKBP5
0,0,37,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,127,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,76,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,75,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,0,0,0,0,0,0,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
6197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6198,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df_test

,TRIB2,FOXC2,SLC25A23,CCNA1,EPHB3,CSF3,MEST,NEGR1,LAMB3,ABCB8,...,TLE4,MPP1,CALCR,AIFM1,MFSD6,TLE1,FOSL2,NOTCH4,JAG1,FKBP5
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,33,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,18,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,0,0,0,0,76,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2542,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2543,0,0,0,0,8,10,0,0,0,59,...,120,0,0,0,0,60,0,43,90,0
2544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
from sklearn.preprocessing import LabelEncoder
X = df
y = df_target
encoder2 = LabelEncoder()
y = encoder2.fit_transform(y)
y

array([ 8, 19, 20, ...,  4, 22, 20])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=156)#shuffle=False,stratify = y, 
print(X_train.shape, X_test.shape)

(4340, 2923) (1861, 2923)

In [22]:
dtrain = xgb.DMatrix(data = X_train, label= y_train)
dtest = xgb.DMatrix(data = X_test, label = y_test)

#Multi-class classification

In [23]:
params = {
    'tree_method': 'approx',
    'objective': 'multi:softprob',
    'num_class': 26
}
num_boost_round = 50

dtrain = xgb.DMatrix(data = X_train, label= y_train)
dtest = xgb.DMatrix(data = X_test, label = y_test)
model = xgb.train(params=params, dtrain=dtrain, num_boost_round=num_boost_round , early_stopping_rounds=5, 
                  evals=[(dtrain, 'train'), (dtest, 'valid')],
                  verbose_eval=2)

[0]	train-mlogloss:2.60579	valid-mlogloss:2.70142
[2]	train-mlogloss:2.21000	valid-mlogloss:2.44574
[4]	train-mlogloss:1.97859	valid-mlogloss:2.32603
[6]	train-mlogloss:1.82044	valid-mlogloss:2.25446
[8]	train-mlogloss:1.69942	valid-mlogloss:2.21104
[10]	train-mlogloss:1.60382	valid-mlogloss:2.18132
[12]	train-mlogloss:1.52782	valid-mlogloss:2.15862
[14]	train-mlogloss:1.46402	valid-mlogloss:2.14455
[16]	train-mlogloss:1.41028	valid-mlogloss:2.13522
[18]	train-mlogloss:1.36348	valid-mlogloss:2.12697
[20]	train-mlogloss:1.32234	valid-mlogloss:2.12518
[22]	train-mlogloss:1.28512	valid-mlogloss:2.12306
[24]	train-mlogloss:1.25173	valid-mlogloss:2.12017
[26]	train-mlogloss:1.22031	valid-mlogloss:2.11900
[28]	train-mlogloss:1.19121	valid-mlogloss:2.11754
[30]	train-mlogloss:1.16500	valid-mlogloss:2.12040
[32]	train-mlogloss:1.13955	valid-mlogloss:2.11786
[33]	train-mlogloss:1.12718	valid-mlogloss:2.11969

In [24]:
params = {
    'tree_method': 'approx',
    'objective': 'multi:softprob',
    'learning_rate': 0.05
}
num_boost_round = 200

clf = xgb.XGBClassifier(n_estimators=num_boost_round, early_stopping_rounds=5, **params) 
clf.fit(X_train, y_train, 
        eval_set=[(X_train, y_train), (X_test,y_test)],
        verbose=2);

[0]	validation_0-mlogloss:3.13733	validation_1-mlogloss:3.15336
[2]	validation_0-mlogloss:2.95628	validation_1-mlogloss:3.00115
[4]	validation_0-mlogloss:2.81826	validation_1-mlogloss:2.89001
[6]	validation_0-mlogloss:2.70562	validation_1-mlogloss:2.80137
[8]	validation_0-mlogloss:2.61027	validation_1-mlogloss:2.72977
[10]	validation_0-mlogloss:2.52781	validation_1-mlogloss:2.67014
[12]	validation_0-mlogloss:2.45410	validation_1-mlogloss:2.61785
[14]	validation_0-mlogloss:2.38835	validation_1-mlogloss:2.57363
[16]	validation_0-mlogloss:2.32881	validation_1-mlogloss:2.53437
[18]	validation_0-mlogloss:2.27495	validation_1-mlogloss:2.50044
[20]	validation_0-mlogloss:2.22488	validation_1-mlogloss:2.46883
[22]	validation_0-mlogloss:2.17854	validation_1-mlogloss:2.44084
[24]	validation_0-mlogloss:2.13606	validation_1-mlogloss:2.41560
[26]	validation_0-mlogloss:2.09667	validation_1-mlogloss:2.39329
[28]	validation_0-mlogloss:2.05923	validation_1-mlogloss:2.37302
[30]	validation_0-mlogloss:2.02487	validation_1-mlogloss:2.35502
[32]	validation_0-mlogloss:1.99176	validation_1-mlogloss:2.33747
[34]	validation_0-mlogloss:1.96106	validation_1-mlogloss:2.32195
[36]	validation_0-mlogloss:1.93166	validation_1-mlogloss:2.30772
[38]	validation_0-mlogloss:1.90388	validation_1-mlogloss:2.29527
[40]	validation_0-mlogloss:1.87801	validation_1-mlogloss:2.28341
[42]	validation_0-mlogloss:1.85286	validation_1-mlogloss:2.27221
[44]	validation_0-mlogloss:1.82912	validation_1-mlogloss:2.26138
[46]	validation_0-mlogloss:1.80623	validation_1-mlogloss:2.25231
[48]	validation_0-mlogloss:1.78471	validation_1-mlogloss:2.24335
[50]	validation_0-mlogloss:1.76397	validation_1-mlogloss:2.23528
[52]	validation_0-mlogloss:1.74417	validation_1-mlogloss:2.22848
[54]	validation_0-mlogloss:1.72520	validation_1-mlogloss:2.22093
[56]	validation_0-mlogloss:1.70665	validation_1-mlogloss:2.21409
[58]	validation_0-mlogloss:1.68937	validation_1-mlogloss:2.20783
[60]	validation_0-mlogloss:1.67274	validation_1-mlogloss:2.20144
[62]	validation_0-mlogloss:1.65639	validation_1-mlogloss:2.19573
[64]	validation_0-mlogloss:1.64091	validation_1-mlogloss:2.19086
[66]	validation_0-mlogloss:1.62578	validation_1-mlogloss:2.18556
[68]	validation_0-mlogloss:1.61133	validation_1-mlogloss:2.18038
[70]	validation_0-mlogloss:1.59748	validation_1-mlogloss:2.17560
[72]	validation_0-mlogloss:1.58378	validation_1-mlogloss:2.17128
[74]	validation_0-mlogloss:1.57037	validation_1-mlogloss:2.16746
[76]	validation_0-mlogloss:1.55770	validation_1-mlogloss:2.16351
[78]	validation_0-mlogloss:1.54534	validation_1-mlogloss:2.16003
[80]	validation_0-mlogloss:1.53335	validation_1-mlogloss:2.15684
[82]	validation_0-mlogloss:1.52207	validation_1-mlogloss:2.15387
[84]	validation_0-mlogloss:1.51100	validation_1-mlogloss:2.15118
[86]	validation_0-mlogloss:1.50007	validation_1-mlogloss:2.14848
[88]	validation_0-mlogloss:1.48928	validation_1-mlogloss:2.14572
[90]	validation_0-mlogloss:1.47909	validation_1-mlogloss:2.14327
[92]	validation_0-mlogloss:1.46919	validation_1-mlogloss:2.14080
[94]	validation_0-mlogloss:1.45928	validation_1-mlogloss:2.13846
[96]	validation_0-mlogloss:1.44978	validation_1-mlogloss:2.13638
[98]	validation_0-mlogloss:1.44072	validation_1-mlogloss:2.13486
[100]	validation_0-mlogloss:1.43147	validation_1-mlogloss:2.13314
[102]	validation_0-mlogloss:1.42272	validation_1-mlogloss:2.13171
[104]	validation_0-mlogloss:1.41435	validation_1-mlogloss:2.13037
[106]	validation_0-mlogloss:1.40631	validation_1-mlogloss:2.12915
[108]	validation_0-mlogloss:1.39795	validation_1-mlogloss:2.12780
[110]	validation_0-mlogloss:1.39018	validation_1-mlogloss:2.12684
[112]	validation_0-mlogloss:1.38253	validation_1-mlogloss:2.12584
[114]	validation_0-mlogloss:1.37461	validation_1-mlogloss:2.12471
[116]	validation_0-mlogloss:1.36696	validation_1-mlogloss:2.12352
[118]	validation_0-mlogloss:1.35972	validation_1-mlogloss:2.12265
[120]	validation_0-mlogloss:1.35260	validation_1-mlogloss:2.12207
[122]	validation_0-mlogloss:1.34558	validation_1-mlogloss:2.12116
[124]	validation_0-mlogloss:1.33861	validation_1-mlogloss:2.12027
[126]	validation_0-mlogloss:1.33191	validation_1-mlogloss:2.11970
[128]	validation_0-mlogloss:1.32523	validation_1-mlogloss:2.11890
[130]	validation_0-mlogloss:1.31880	validation_1-mlogloss:2.11838
[132]	validation_0-mlogloss:1.31236	validation_1-mlogloss:2.11797
[134]	validation_0-mlogloss:1.30603	validation_1-mlogloss:2.11788
[136]	validation_0-mlogloss:1.30004	validation_1-mlogloss:2.11782
[138]	validation_0-mlogloss:1.29401	validation_1-mlogloss:2.11753
[140]	validation_0-mlogloss:1.28819	validation_1-mlogloss:2.11747
[142]	validation_0-mlogloss:1.28247	validation_1-mlogloss:2.11714
[144]	validation_0-mlogloss:1.27672	validation_1-mlogloss:2.11726
[146]	validation_0-mlogloss:1.27109	validation_1-mlogloss:2.11678
[148]	validation_0-mlogloss:1.26557	validation_1-mlogloss:2.11671
[150]	validation_0-mlogloss:1.26014	validation_1-mlogloss:2.11673
[152]	validation_0-mlogloss:1.25457	validation_1-mlogloss:2.11640
[154]	validation_0-mlogloss:1.24922	validation_1-mlogloss:2.11619
[156]	validation_0-mlogloss:1.24407	validation_1-mlogloss:2.11594
[158]	validation_0-mlogloss:1.23885	validation_1-mlogloss:2.11532
[160]	validation_0-mlogloss:1.23376	validation_1-mlogloss:2.11514
[162]	validation_0-mlogloss:1.22895	validation_1-mlogloss:2.11459
[164]	validation_0-mlogloss:1.22389	validation_1-mlogloss:2.11432
[166]	validation_0-mlogloss:1.21899	validation_1-mlogloss:2.11436
[168]	validation_0-mlogloss:1.21420	validation_1-mlogloss:2.11432
[170]	validation_0-mlogloss:1.20944	validation_1-mlogloss:2.11441
[171]	validation_0-mlogloss:1.20708	validation_1-mlogloss:2.11472

In [25]:
y_true = y_test
y_pred = clf.predict(X_test)
y_score = clf.predict_proba(X_test)
y_true.shape, y_pred.shape, y_score.shape

((1861,), (1861,), (1861, 26))

In [52]:
from sklearn import metrics 
metrics.accuracy_score(y_true, y_pred)

0.34712520150456744

In [27]:
from sklearn import metrics 
metrics.accuracy_score(y_true, y_pred)

0.3444384739387426

In [28]:
print(metrics.classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.70      0.74        23
           1       0.38      0.14      0.21        35
           2       0.27      0.65      0.38       238
           3       0.10      0.03      0.04        39
           4       0.62      0.65      0.64        63
           5       1.00      0.12      0.22        16
           6       0.34      0.31      0.33       150
           7       0.26      0.23      0.25        60
           8       0.27      0.36      0.31       159
           9       0.06      0.04      0.05       104
          10       0.93      0.29      0.44        48
          11       0.27      0.42      0.33        57
          12       0.31      0.17      0.22        48
          13       0.25      0.07      0.11        59
          14       0.41      0.18      0.25        49
          15       0.31      0.49      0.38        93
          16       0.07      0.04      0.05        28
          17       0.18      0.05      0.08        37
          18       0.24      0.10      0.14        81
          19       0.23      0.09      0.13        53
          20       0.78      0.61      0.68        82
          21       0.30      0.25      0.27       109
          22       0.30      0.26      0.28        38
          23       0.76      0.61      0.67       102
          24       0.29      0.08      0.13        24
          25       0.65      0.42      0.51        66

    accuracy                           0.34      1861
   macro avg       0.40      0.28      0.30      1861
weighted avg       0.37      0.34      0.33      1861

In [29]:
metrics.roc_auc_score(y_true, y_score, average='weighted', multi_class='ovr')

0.8541877349290403

In [54]:
clf.predict(df_test)

array([21, 25,  2, ..., 25, 10,  6])

In [30]:
res = clf.predict(df_test)

In [31]:
res = encoder2.inverse_transform(res)

In [32]:

df_test1 = pd.read_csv('test.csv')
res_df = pd.DataFrame ({'ID' : df_test1['ID'], 'SUBCLASS' : res})
res_df

             ID SUBCLASS
0     TEST_0000     STES
1     TEST_0001     UCEC
2     TEST_0002     THCA
3     TEST_0003      LGG
4     TEST_0004     STES
...         ...      ...
2541  TEST_2541     COAD
2542  TEST_2542     HNSC
2543  TEST_2543     SKCM
2544  TEST_2544     LAML
2545  TEST_2545      LGG

[2546 rows x 2 columns]

In [33]:
res_df.SUBCLASS.value_counts()

SUBCLASS
BRCA      618
COAD      537
KIPAN     218
STES      142
OV        141
GBMLGG    139
UCEC       92
SKCM       83
THCA       79
LGG        71
HNSC       67
LIHC       51
KIRC       46
TGCT       37
LAML       36
PRAD       31
CESC       30
BLCA       23
LUAD       22
LUSC       19
SARC       15
PAAD       14
ACC        13
PCPG       12
THYM        7
DLBC        3
Name: count, dtype: int64

In [34]:
res_df.to_csv('v3.csv',index = False)

In [97]:
pred_probs = xgb_model.predict(dtest)

NameError: name 'xgb_model' is not defined

In [ ]:
import numpy as np
print(np.round(pred_probs[:10], 3))

In [58]:
preds= [round(x) if x > 0 else 0 for x in pred_probs]

In [ ]:
preds

In [60]:
for p in preds:
    if p<0:
        print(p)

In [ ]:
encoder.inverse_transform(preds)

In [35]:
model = RandomForestClassifier(
            n_estimators=50, ## 붓스트랩 샘플 개수 또는 base_estimator 개수
            criterion='entropy', ## 불순도 측도
            max_depth=65, ## 개별 나무의 최대 깊이
            #max_features='sqrt', ## 매 분리시 랜덤으로 뽑을 변수 개수
            #max_samples=1.0, ## 붓스트랩 샘플 비율 => 1이면 학습데이터를 모두 샘플링한다.
            #bootstrap=True, ## 복원 추출,  False이면 비복원 추출
            oob_score=True, ## Out-of-bag 데이터를 이용한 성능 계산
            random_state=100
).fit(X,y)

In [ ]:
## 예측
print(model.predict(X)[:3]) 
print()

In [ ]:
X[:3]

In [ ]:
## 성능 평가
print(model.oob_score_) ## Out-of-bag 성능 평가 점수
print('정확도 : ', model.score(X,y)) ## 테스트 성능 평가 점수(Accuracy)
print()
## 변수 중요도
print(model.feature_importances_)

In [ ]:
## 성능 평가
print(model.oob_score_) ## Out-of-bag 성능 평가 점수
print('정확도 : ', model.score(X,y)) ## 테스트 성능 평가 점수(Accuracy)
print()
## 변수 중요도
print(model.feature_importances_)

In [ ]:
res = model.predict(df_test)
res

In [ ]:
res = model.predict(df_test)
res

In [ ]:
df_test1 = pd.read_csv('test.csv')
res_df = pd.DataFrame ({'ID' : df_test1['ID'], 'SUBCLASS' : res})
res_df

In [24]:
res_df.to_csv('res04.csv',index = False)

In [ ]:
df[df.SUBCLASS == 'BRCA'].sum().sort_values(ascending=False).str.replace('WT','')

In [ ]:
df[df['SUBCLASS']=='DLBC']

In [ ]:
import numpy as np 
dfs = df[df['SUBCLASS']=='DLBC']
dfs.columns

In [ ]:
for c in dfs.columns:
    dfs[c] = np.where(dfs[c] == 'WT', 0, 1)
dfs

In [ ]:
dfs = df[df['SUBCLASS']=='DLBC']
dfs.apply(lambda x: x(if x=='WT' else x=1))

In [ ]:
for  x in df.iloc[0]:
    if x != 'WT': print(x)

In [ ]:
len(df_test.columns)

In [ ]:
len(df_test)

In [37]:
a1 = ['DDX10', 'ELOVL5']
a2 = ['AAAS', 'ABCB4', 'ABCC1', 'ABCC4', 'ABL1', 'ACKR3', 'ACOX2', 'ACSL1', 'ACSS2', 'ACVR1B', 'ADAD1', 'ADAM10', 'ADAM2', 'ADAMTS5', 'ADCY2', 'ADH5', 'ADIPOQ', 'AGO4', 'AHNAK', 'AIFM3', 'AKAP12', 'ALAS1', 'ALDH1A1', 'ALDH2', 'ALS2', 'ANLN', 'ARHGEF7', 'ATAD2', 'ATP1A1', 'ATP7A', 'ATXN1', 'AUTS2', 'AVPR1A', 'AXIN2', 'BAZ2A', 'BIRC2', 'BRAF', 'BTBD3', 'CACNA1A', 'CACNA1H', 'CAMKK2', 'CASP8', 'CAST', 'CCR5', 'CCT6A', 'CD302', 'CD47', 'CD7', 'CDADC1', 'CDH13', 'CDH16', 'CDH3', 'CDH4', 'CDK5RAP2', 'CDON', 'CELSR1', 'CELSR2', 'CENPJ', 'CKAP4', 'CLDN9', 'COL11A1', 'COL16A1', 'COL2A1', 'COL5A1', 'CORO1A', 'CPT1A', 'CREBBP', 'CSTF3', 'CTSB', 'CTSV', 'CTTN', 'CXCR3', 'CYP2C18', 'DAAM1', 'DDX10', 'DGCR8', 'DHRS2', 'DIO1', 'DLC1', 'DLK2', 'DNM1L', 'DOCK10', 'DOCK2', 'DSC3', 'DST', 'DUSP6', 'DVL2', 'DYRK1A', 'DYRK3', 'EIF3A', 'EIF4G3', 'ELL', 'ELOVL5', 'ELOVL6', 'ENO1', 'ERN1', 'ESR1', 'EVL', 'EWSR1', 'EXO1', 'EZR', 'F12', 'F5', 'FADS2', 'FBXO9', 'FBXW7', 'FCN1', 'FEN1', 'FGD6', 'FKBP4', 'FLNA', 'FLNB', 'FN1', 'FSCN1', 'FXN', 'GEMIN4', 'GJB3', 'GMPR2', 'GPD1', 'GPI', 'GPRC5C', 'GSS', 'HSPB1', 'HUWE1', 'ICAM5', 'IDH2', 'IDH3G', 'IGF1R', 'IL17RA', 'IL1RL1', 'IL6', 'IPO4', 'IRF9', 'IRS4', 'ISG20L2', 'ISL1', 'ITIH5', 'ITPK1', 'JAG2', 'JUP', 'KALRN', 'KCND1', 'KDM3A', 'KIF3C', 'KIF5B', 'KIFAP3', 'KLF10', 'KMT2D', 'KRT15', 'KRT31', 'LAMA1', 'LAMA3', 'LAMB3', 'LGALS3BP', 'LIG1', 'LRP1', 'LTBP1', 'LTF', 'LUM', 'MAP3K1', 'MAP4K1', 'MAPKAP1', 'MAST3', 'MCCC1', 'MEF2D', 'MEIS2', 'MLF1', 'MMP15', 'MMP16', 'MMP2', 'MMP9', 'MPI', 'MVK', 'MYH10', 'MYH3', 'MYH9', 'MYOT', 'NAV2', 'NCOA3', 'NCSTN', 'NDST2', 'NDUFAF4', 'NET1', 'NINJ1', 'NKX3-1', 'NMI', 'NOD1', 'NOLC1', 'NOS2', 'NOTCH2', 'NTRK3', 'NUFIP1', 'NXF1', 'ODF2', 'OLFM1', 'P2RY1', 'PAIP1', 'PCDHB1', 'PCM1', 'PEG3', 'PEX12', 'PFKL', 'PHF3', 'PHGDH', 'PHKA2', 'PIK3CD', 'PKHD1', 'PLAGL1', 'PLEC', 'PLXNB1', 'PPARGC1A', 'PRKCB', 'PTCH1', 'PTPN6', 'PTPRC', 'PTPRG', 'PTPRM', 'PYGL', 'RET', 'RHOT1', 'ROCK1', 'ROS1', 'RPL3L', 'RXRG', 'RYR1', 'RYR2', 'SCARB1', 'SCN9A', 'SCUBE2', 'SEC14L1', 'SEC24D', 'SFRP1', 'SHROOM2', 'SIDT1', 'SLC12A3', 'SLC35A3', 'SLC39A6', 'SLC6A12', 'SLC6A9', 'SLC7A1', 'SLN', 'SMAD1', 'SMC1A', 'SMC3', 'SMC4', 'SMOX', 'SMTN', 'SNAPC4', 'SPTAN1', 'SREBF2', 'ST14', 'STAB1', 'STAG3', 'STARD3', 'STAU1', 'SVIL', 'SYNJ2', 'TAOK2', 'TCF7L2', 'TDO2', 'TEAD4', 'TFDP1', 'TG', 'THBD', 'THBS3', 'TIMELESS', 'TIMM10', 'TJP3', 'TK1', 'TLE4', 'TM7SF3', 'TMEM164', 'TNC', 'TNFRSF1A', 'TNIP1', 'TNIP2', 'TOP1', 'TRIB2', 'TSC1', 'TSPYL2', 'TUBA3C', 'TXNRD2', 'TYK2', 'UBE2D1', 'UBE2L6', 'UNC13B', 'UNC5C', 'UQCRB', 'USO1', 'WEE1', 'WNT1', 'WWC1', 'XPC', 'YWHAZ', 'ZNF292', 'ZNFX1']
set(a1).intersection(set(a2))

{'DDX10', 'ELOVL5'}

In [39]:
a1[0] in a2

True

In [44]:
df.shape[0]

6201

In [75]:
df.iloc[4984:4985].iloc[:, 2:].replace('WT', '').

A2M
AAAS     R194Q
AADAT
AARS1
ABAT
         ...
ZNRF4
ZPBP
ZW10
ZWINT
ZYX      A525T
Length: 4384, dtype: object

In [78]:
to_compare = ['DDX10', 'ELOVL5']
for i in range(0, df.shape[0]): 
    
    bset = set()
    
    row = df.iloc[i:i+1].iloc[:, 2:]#remove ID,SUBCLASS
    count_df = row.apply(lambda x : x!='WT').agg(sum).reset_index(name='count')
    g_setl = count_df.loc[count_df['count'] > 0]['index']
    
    if to_compare[0] in set(g_setl):
        print(i)
        print( set(to_compare).intersection(set(g_setl)) )
        for a in to_compare: 
            bset.add(row[a].values[0])
        print(bset)
        print()

244
{'DDX10'}
{'WT', 'E186Q'}

286
{'DDX10'}
{'WT', 'Y292D'}

379
{'DDX10'}
{'WT', 'L128L'}

406
{'DDX10'}
{'WT', 'E445* E466* E750D'}

562
{'DDX10'}
{'WT', 'P436L'}

601
{'DDX10'}
{'WT', 'E580*'}

680
{'DDX10'}
{'WT', 'M825T'}

1120
{'DDX10'}
{'WT', 'E658*'}

1202
{'DDX10', 'ELOVL5'}
{'Q622H', 'S149S'}

1233
{'DDX10'}
{'WT', 'E712D'}

1476
{'DDX10'}
{'K119R', 'WT'}

1489
{'DDX10'}
{'WT', 'Q704H'}

1789
{'DDX10'}
{'WT', 'Q462P Y551* K665R'}

1883
{'DDX10'}
{'P421L', 'WT'}

1924
{'DDX10'}
{'WT', 'A613T'}

2133
{'DDX10'}
{'WT', 'D808D'}

2189
{'DDX10'}
{'WT', 'E591A'}

2377
{'DDX10'}
{'WT', 'M825T'}

2463
{'DDX10'}
{'WT', 'S171* E864K'}

2484
{'DDX10'}
{'S302G', 'WT'}

2690
{'DDX10'}
{'WT', 'A113T'}

2707
{'DDX10'}
{'WT', 'S474C'}

2713
{'DDX10'}
{'WT', 'K410K'}

2732
{'DDX10'}
{'WT', 'K737E'}

3246
{'DDX10'}
{'WT', 'R265H'}

3528
{'DDX10'}
{'D849Y', 'WT'}

3666
{'DDX10'}
{'WT', 'T819I'}

4081
{'DDX10'}
{'WT', 'K78R R309I E547*'}

4210
{'DDX10'}
{'WT', 'T621T'}

4228
{'DDX10'}
{'WT', 'A122T'}

4303
{'DDX10'}
{'WT', 'V294V'}

4568
{'DDX10'}
{'A529V', 'WT'}

4656
{'DDX10', 'ELOVL5'}
{'R100H', 'S117S'}

4757
{'DDX10'}
{'R467I D806Y', 'WT'}

4832
{'DDX10'}
{'WT', 'A113T'}

4984
{'DDX10', 'ELOVL5'}
{'E123*', 'V450A D588N E618*'}

5049
{'DDX10', 'ELOVL5'}
{'T140M', 'D215N'}

5502
{'DDX10'}
{'WT', 'E693K'}

5575
{'DDX10'}
{'WT', 'K743fs'}

5683
{'DDX10'}
{'WT', 'A415T E567K F690C'}

5707
{'DDX10'}
{'WT', 'T610I'}

5772
{'DDX10'}
{'WT', 'K600K'}

5924
{'DDX10'}
{'WT', 'R90H'}

6081
{'DDX10'}
{'R133C', 'WT'}

6140
{'DDX10'}
{'K163Q', 'WT'}

6172
{'DDX10'}
{'WT', 'H346Y'}

In [ ]:

1202
{'DDX10', 'ELOVL5'}
{'Q622H', 'S149S'}


4656
{'DDX10', 'ELOVL5'}
{'R100H', 'S117S'}

4984
{'DDX10', 'ELOVL5'}
{'E123*', 'V450A D588N E618*'}

5049
{'DDX10', 'ELOVL5'}
{'T140M', 'D215N'}

In [ ]:
G503V L179R

In [79]:
df.iloc[1202]

ID           TRAIN_1202
SUBCLASS           UCEC
A2M               L311P
AAAS                 WT
AADAT                WT
               ...
ZNRF4                WT
ZPBP        V219I R115H
ZW10                 WT
ZWINT                WT
ZYX               P260T
Name: 1202, Length: 4386, dtype: object

In [80]:
df.iloc[4656]

ID          TRAIN_4656
SUBCLASS          COAD
A2M                 WT
AAAS             P516L
AADAT               WT
               ...
ZNRF4               WT
ZPBP                WT
ZW10                WT
ZWINT               WT
ZYX                 WT
Name: 4656, Length: 4386, dtype: object

In [81]:
df.iloc[4984]

ID          TRAIN_4984
SUBCLASS          UCEC
A2M                 WT
AAAS             R194Q
AADAT               WT
               ...
ZNRF4               WT
ZPBP                WT
ZW10                WT
ZWINT               WT
ZYX              A525T
Name: 4984, Length: 4386, dtype: object

In [82]:
df.iloc[5049]

ID           TRAIN_5049
SUBCLASS           UCEC
A2M         K271N N159Y
AAAS                 WT
AADAT                WT
               ...
ZNRF4                WT
ZPBP                 WT
ZW10              S161Y
ZWINT                WT
ZYX                  WT
Name: 5049, Length: 4386, dtype: object

In [56]:
to_compare[1]

'ELOVL5'