In [1]:
import pandas as pd 
df = pd.read_csv ('../input/train.csv')
df_test = pd.read_csv('../input/test.csv')
data = df.copy()
data = df.drop(columns = ['ID', 'SUBCLASS'], axis=1)

In [4]:
groups = {
    'group1': ['KIPAN', 'KIRC'],
    'group2': ['SARC', 'HNSC', 'STES', 'PAAD', 'OV', 'LIHC', 'LUSC', 'LUAD'],  # TP53
    'group3': ['GBMLGG', 'LGG'],  # IDH1, TP53
    'group4': ['BRCA', 'CESC'],  # Pik3ca
    'group5': ['THCA', 'SKCM'],  # BRAF
    'group6': ['DLBC', 'BLCA'],  # KMT2D, TP53, etc.
    'group7': ['THYM', 'PCPG'],  # HRAS
    'group8': ['PRAD', 'UCEC', 'LAML', 'COAD', 'ACC', 'TGCT']
}

In [12]:
cgs = pd.read_csv('../input/cancer-genes.csv')
cset =  set(cgs['c.genes'].values)

In [ ]:
dgs = dict()

In [13]:
df_test = df_test.drop('ID', axis=1) 
df_test

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
1,WT,WT,WT,WT,WT,R587Q,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,I383Sfs,WT,WT,WT,WT
2,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
3,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
4,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2542,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2543,WT,WT,WT,WT,WT,L217I,P221P P251P,R5M,G606D,I248Nfs,...,S2049Vfs S1909Vfs,L232R,WT,WT,L305L,WT,N252I N251I,G679V,WT,WT
2544,WT,WT,WT,WT,WT,WT,WT,WT,R1517H,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
2545,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [14]:
non_wt_counts = (df_test != 'WT').sum()

In [20]:
df_test.drop(columns = non_wt_counts[non_wt_counts==0].index, inplace=True)

In [31]:
d = 'KIPAN'
disease_df = data[df["SUBCLASS"] == d]
disease_df

,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,ABCA4,ABCA5,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
16,WT,WT,WT,WT,WT,WT,WT,WT,C886G,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
17,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
59,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
66,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,S196G,WT,WT,WT,WT,WT
6137,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6163,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6186,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT
6194,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT,...,WT,WT,WT,WT,WT,WT,WT,WT,WT,WT

In [41]:
non_wt_counts = (disease_df != 'WT').sum()  # "WT"가 아닌 행 개수
nsorted = non_wt_counts.sort_values(ascending=False) #빈도 수가 높은 순서대로 정렬
print(d)
gls = nsorted.reset_index(name='count')
a1 = set(gls[gls['count']>0]['index'])
#a1
#gls

KIPAN

In [ ]:
for d in df['SUBCLASS'].unique():
    disease_df = data[df["SUBCLASS"] == d]
    non_wt_counts = (disease_df != 'WT').sum()  # "WT"가 아닌 행 개수
    nsorted = non_wt_counts.sort_values(ascending=False) #빈도 수가 높은 순서대로 정렬
    gls = nsorted.reset_index(name='count')
    a1 = set(gls[gls['count']>0]['index'])
    dgs[d]

In [46]:
len(a1)

3008

In [47]:
len(a1.intersection(cset))

306

In [48]:
len(set(df_test.columns).intersection(cset))

368

In [49]:
len(set(df.columns).intersection(cset))

368