In [3]:
"asdf".join("gkgkgk")

'gasdfkasdfgasdfkasdfgasdfk'

In [7]:
import pandas as pd

# 예시 데이터프레임 생성
df = pd.DataFrame({
    'col1': ['apple', 'WT', 'banana', 'wtcherry'],
    'col2': ['orange', 'WT', 'peach', 'plum'],
    'col3': ['WT', 45.6, 'wtapple', 'pear']
})

# 각 셀에 대해 조건을 적용하여 값 변경 (value가 'WT'면 '', 아니면 컬럼명+첫 글자/숫자)
def process_cell(value, col_name):
    if value == 'WT':  # 값이 'WT'이면 빈 문자열
        return ''
    elif isinstance(value, str):  # 문자열일 때는 첫 글자 + 컬럼명
        return col_name + value[0]
    elif isinstance(value, (int, float)):  # 숫자일 때는 첫 숫자(소수점 전) + 컬럼명
        return col_name + str(value)[0]
    return value  # 그 외에는 원래 값 반환

# 각 셀을 처리하는 함수 적용
for col in df.columns:
    df[col] = df[col].apply(lambda x: process_cell(x, col))

print(df)

    col1   col2   col3
0  col1a  col2o
1                col34
2  col1b  col2p  col3w
3  col1w  col2p  col3p

In [34]:
from sklearn.feature_selection import SelectKBest, chi2
df = pd.DataFrame({
    'a': [1, 0, 1, 0],
    'b': [0, 1, 0, 1],
    'c': [1, 1, 0, 1],
    'd': [0, 0, 1, 1],
    'e': [1, 0, 1, 0],
    'f': [0, 0, 0, 1],
    'g': [1, 1, 1, 0],
    'class': [0, 1, 2, 3],
    
})
# X는 입력 데이터 (특징), y는 레이블 (클래스)
X = df[['a', 'b', 'c', 'd', 'e', 'f']]
y = df['class']  # 'A' 또는 'B'의 클래스

# 카이제곱 검정을 사용하여 상위 K개의 중요한 특징 선택
selector = SelectKBest(chi2, k=3)  # 상위 3개의 중요한 컬럼 선택
X_new = selector.fit_transform(X, y)

print(X.columns[selector.get_support()])

Index(['d', 'e', 'f'], dtype='object')

In [37]:

import pandas as pd 
df = pd.read_csv('../input/train.csv')

#data = df.applymap(lambda x : 0 if x=='WT' else 1)

In [38]:
df.iloc[:, 2:] = df.iloc[:, 2:].applymap(lambda x : 0 if x=='WT' else 1)
df

/var/folders/91/x1jkjm3549s21y3h3k_k56q80000gn/T/ipykernel_2485/1184962331.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.iloc[:, 2:] = df.iloc[:, 2:].applymap(lambda x : 0 if x=='WT' else 1)

,ID,SUBCLASS,A2M,AAAS,AADAT,AARS1,ABAT,ABCA1,ABCA2,ABCA3,...,ZNF292,ZNF365,ZNF639,ZNF707,ZNFX1,ZNRF4,ZPBP,ZW10,ZWINT,ZYX
0,TRAIN_0000,KIPAN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,TRAIN_0001,SARC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,TRAIN_0002,SKCM,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,TRAIN_0003,KIRC,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,TRAIN_0004,GBMLGG,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6196,TRAIN_6196,LUAD,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6197,TRAIN_6197,LGG,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6198,TRAIN_6198,COAD,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6199,TRAIN_6199,TGCT,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6200,TRAIN_6200,SKCM,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
disease_list = df.SUBCLASS.unique()

In [40]:
from sklearn.feature_selection import SelectKBest, chi2
# X는  1,0 으로 만 이뤄진

X = data # df.iloc[:, 2: ]
y = df['SUBCLASS']  # 'A' 또는 'B'의 클래스

# 카이제곱 검정을 사용하여 상위 K개의 중요한 특징 선택
selector = SelectKBest(chi2, k=500)  # 상위 3개의 중요한 컬럼 선택
X_new = selector.fit_transform(X, y)
res = X.columns[selector.get_support()]
print(res)

Index(['A2M', 'ABCA2', 'ABCA3', 'ABCA4', 'ABCA6', 'ABCA8', 'ABCA9', 'ABCB1',
       'ABCB11', 'ABCC1',
       ...
       'VWA5A', 'VWF', 'WIZ', 'WWC1', 'XDH', 'XYLT2', 'ZBTB16', 'ZEB1',
       'ZFPM2', 'ZNF292'],
      dtype='object', length=500)

In [41]:
len(list(res))

500